#ifndef INTERFACE_H
#define INTERFACE_H

#include <raygui.h>

#include "defs.h"
#include "synth.h"

/* Parameters of the application, used for rendering and tuning */
typedef 
struct 
{
    float *attack, *decay, *sustain, *release;
    adsr_t *filter_envelope;
    synth_t *synth;
    int *dropbox_a, *dropbox_b, *dropbox_c; 
    bool *dropbox_a_b, *dropbox_b_b, *dropbox_c_b;
} params_t;

/*
 * Renders the global informations and menus about the synthesizer :
 * - ADSR envelope sliders
 * - Filter ADSR envelope sliders
 * - Oscillator waveforms dropdown menus
 * - Filter cutoff and filter envelope ON/OFF
 * - Amplification and detune effect
 */
void 
render_informations(params_t *params);

/* Renders the waveform generated by the render_synth function */
void
render_waveform(short *buffer);

/* Render the white keys from the MIDI piano visualizer */
void 
render_white_keys();

/* Render the black keys from the MIDI piano visualizer */
void 
render_black_keys();

/* Renders given note into a pressed key in the MIDI piano visualizer */
void 
render_key(int midi_note);

/* Outputs a given MIDI note rectangle parameters (x, y, width and height) */
void 
get_key_position(int midi_note, int *x, int *y,
                 int *width, int *height, int *is_black);

/* Returns if a MIDI note is a assigned to a black key or not */
int 
is_black_key(int midi_note);


#endif